name: ghrs
on:
  schedule:
    # Run this once per day.
    # The specific hour is interpreted in UTC time zone.
    # Do this towards the end of the UTC day.
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  j1:
    name: github-repo-stats
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repositories to generate reports for.
        statsRepo: ['IceFireDB/IceFireDB','IceFireDB/redhub','IceFireDB/IceFireDB-Proxy', 'RedTimeDB/RedTimeProxy','FlowShield/flowshield']
    steps:
      - name: github-repo-stats
        uses: jgehrcke/github-repo-stats@v1.3.0
        with:
          ghpagesprefix: https://gitsrc.github.io/icefiredb-status
          repository: ${{ matrix.statsRepo }}
          # Required token privileges: Can read the target
          # repo, and can push to the repository this
          # workflow file lives in (to store data and
          # the report files).
          ghtoken: ${{ secrets.ghrs_github_api_token }}
